### ISSUE TITLE
podcasts have many episodes

### ISSUE THREAD

**Issue by chrisns** [DaftDoris/newsdesk#109]
- [ ] router includes data
- [ ] defaults to show $tomorrow
- [ ] can navigate forwards and backwards through episodes
- [ ] only applies to SCRIPT and DRAFT. Inbox remains consistent throughout

**Comment by mrjamieeast** [comment]
This doesn't appear to be working @chrisns @bhavinsen unless i'm missing something? I cannot select a different podcast? Every date has the same content in DRAFT and SCRIPT
