### ISSUE TITLE
INBOX: Truncate URL links to 50chars

### ISSUE THREAD

**Issue by mrjamieeast** [DaftDoris/newsdesk#169]
eg. 
FROM: https://twitter.com/PoliticusSarah/status/1520759587128979458?s=20&t=-ZSrWH2DIXO97dJgtoy46Q

TO:
https://twitter.com/PoliticusSarah/status/15207595...

**Comment by chrisns** [comment]
Not to: @PoliticusSarah/15207595 ?

**Comment by mrjamieeast** [comment]
Won’t always be a twitter link though.

I’m looking at baking in our custom bitly via an API - daftdor.is/1234 <http://daftdor.is/1234>

Jamie East
THE SMART 7
T: +44 7515 340555
@jamieeast
www.thesmart7.com
Listen to the latest episode <http://podfollow.com/thesmart7>

**Comment by chrisns** [comment]
Yeah. It's mostly Twitter, so shorten to that first, the. Do your shortener. It's only changing how it looks. The actual link is the same.
You can loose the http(s) www .com and anything after a ? Or #

**Comment by chrisns** [comment]
needs some thought into how this will work, perhaps expand the link fully when editing, but when it loses focus truncate?

**Comment by mrjamieeast** [comment]
Yeah can do - although the URL is not important to workflow as long as it can be clicked on
