### ISSUE TITLE
SCRIPT7: Create ability to send SCRIPT item to different PODCAST EPISODE

### ISSUE THREAD

**Issue by mrjamieeast** [DaftDoris/newsdesk#246]
A user may need to defer a STORY for another podcast episode (embargo reasons). Clicking the bookmark icon will generate a box with a list of dates to choose from.

This SENDS a separate COPY of the STORY to the PODCAST edition

**Comment by chrisns** [comment]
current by design work around, send to inbox, go to date move out of inbox. do we need a workflow/feature/capability for this?
