### ISSUE TITLE
Use updateDoc instead of setDoc

### ISSUE THREAD

**Issue by mrjamieeast** [DaftDoris/newsdesk#271]
in order to avoid users losing work, please implement : { updateDoc() } catch (e) { if (e.message === “ref doesn’t exist”) setDoc() else throw (e)}

wherever setDoc is currently used.

**Comment by chrisns** [comment]
https://firebase.google.com/docs/firestore/manage-data/add-data#update_elements_in_an_array

See using arrayUnion and arrayRemove
