### ISSUE TITLE
BUG: DRAFT dragging URLs into numbers being weird

### ISSUE THREAD

**Issue by mrjamieeast** [DaftDoris/newsdesk#356]
Pasting a URL into an existing item does not work - it disappears. Please see video

https://user-images.githubusercontent.com/104105362/175081842-4bd260a8-4081-4188-b48b-e2e24e93d676.mov

.

**Comment by ArindamReact** [comment]
Not able to replicate issue

[ice_video_20220809-122937.webm](https://user-images.githubusercontent.com/105204781/183597623-40401af8-7adf-49f2-9624-017a97bb342e.webm)

**Comment by mrjamieeast** [comment]
https://user-images.githubusercontent.com/104105362/184591363-f9be164d-d4fa-4d41-9a7a-543c9ff3372a.mov
