### ISSUE TITLE
INBOX: Ability to DELETE an item from INBOX

### ISSUE THREAD

**Issue by mrjamieeast** [DaftDoris/newsdesk#369]

**Comment by ArindamReact** [comment]
Hello @mrjamieeast this is working on main branch, please let me know why this card is still in buglist
[screencast-nimbus-capture-2022.08.28-22_05_18.webm](https://user-images.githubusercontent.com/105204781/187084803-29a65587-5bc7-4a96-9d72-feccda84d623.webm)

**Comment by mrjamieeast** [comment]
Because I’ve merged and pushed it live a long time ago yet it is not showing on live site.
