### ISSUE TITLE
SCRIPT: ADD A "STILL TO COME" FIELD

### ISSUE THREAD

**Issue by mrjamieeast** [DaftDoris/newsdesk#520]
Between ITEMS 4 and 3 please put a single input area as per design - wit STILL TO COME in it.
See Figma - also screengrab
<img width="636" alt="Screenshot 2022-08-24 at 07 26 50" src="https://user-images.githubusercontent.com/104105362/186346458-cb98527e-5732-49e9-85d6-9ed575559233.png">

**Comment by ArindamReact** [comment]
Do we need  this  "STILL TO COME" after every slot?  @mrjamieeast

**Comment by mrjamieeast** [comment]
No - just in between 4 & 3 please

**Comment by mrjamieeast** [comment]
No only after “4” before “3”
